import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <AuthProvider>
          {/* 全体をAuthContextでラップ */}
          <div className="flex">
            <Sidebar /> {/* サイドバーを配置 */}
            <div className="flex-grow ml-64">
              {/* サイドバーの幅に合わせてマージンを設定 */}
              {children} {/* 各ページの内容がここにレンダリングされる */}
            </div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
